name: C/C++ CI - Build Status

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: OUTPUT
      run: gcc Airlines.h Airlines.c Airlines1.c Airlines2.c Airlines3.c -o OUTPUT
