name: C/C++ CI - Build Status

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: gcc Airlines.h Airlines.c Airlines1.c Airlines2.c Airlines3.c -o OUTPUT
    - name: Run
      run: .\OUTPUT.exe


