name: Code Quality - Static Code - Cppcheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cppcheck:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
